#define PIN_SENSOR_LINE_1 2
#define PIN_SENSOR_LINE_2 3
#define PIN_SENSOR_ULTRASONIC_TRIGGER 4 
#define PIN_SENSOR_ULTRASONIC_ECHO 5
#define PIN_MOTOR_AIN_1 13
#define PIN_MOTOR_AIN_2 12
#define PIN_MOTOR_PWMA 11 // Must be on PWM pin
#define PIN_MOTOR_STBY 7
#define PIN_MOTOR_BIN_1 8
#define PIN_MOTOR_BIN_2 9
#define PIN_MOTOR_PWMB 10 // Must be on PWM pin